name: verification

on:
  push:
  pull_request:

jobs:
  host:
    runs-on: ubuntu-latest
    env:
      OMP_NUM_THREADS: 4
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Repository verification
        run: make verify
